source 'https://rubygems.org'

group :development do
  gem 'codeclimate-test-reporter'
  gem 'rake', '>= 12.3.3'
  gem 'redcarpet', '>= 3.5.1'
  gem 'rspec'
  gem 'rubocop', '>= 0.49.0'
  gem 'rubocop-rspec'
  gem 'rubyzip', '>= 1.3.0'
  gem 'simplecov'
  gem 'tee'
  gem 'webmock'
  gem 'yard', '>= 0.9.20'
end
