*&---------------------------------------------------------------------*
*&  Include           ZCAE_EDWHAE_SURVEY_SC
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1
  WITH FRAME TITLE text-s01.

* START OF RADIO BUTTON SELECTION
* Selection Block for Radio Button Delta & Full.

  SELECTION-SCREEN BEGIN OF BLOCK b2
  WITH FRAME TITLE text-s05.
* SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS: p_delta RADIOBUTTON GROUP rb1 USER-COMMAND fchg DEFAULT 'X'.
*  SELECTION-SCREEN COMMENT 3(20) text-s06 FOR FIELD p_delta.
*  SELECTION-SCREEN POSITION 50.
  PARAMETERS: p_full RADIOBUTTON GROUP rb1 .
*  SELECTION-SCREEN COMMENT 53(20) text-s07 FOR FIELD p_full.
*  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b2.
* END OF RADIO BUTTON SELECT
  SELECTION-SCREEN BEGIN OF BLOCK b5
  WITH FRAME TITLE text-s14.

** START FOR TIMESTAMP
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(22) text-s14 FOR FIELD p_tstp.
*  PARAMETERS: p_datfr TYPE dats.
  PARAMETERS : p_tstp TYPE crmd_orderadm_h-created_at.
*  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK b5.
* END OF TIME INTERVAL

* START OF FILE NAME PARAMETERS

  SELECTION-SCREEN BEGIN OF BLOCK b3
  WITH FRAME TITLE text-s11.
*  SELECTION-SCREEN SKIP.

*for header file name.
*  SELECTION-SCREEN BEGIN OF LINE.

*  SELECTION-SCREEN COMMENT 3(27) text-077 FOR FIELD p_head.
  PARAMETERS: p_head TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_head.
*  SELECTION-SCREEN END OF LINE.

* FOR SURVEY FILE NAME.
*  SELECTION-SCREEN BEGIN OF LINE.

*  SELECTION-SCREEN COMMENT 3(27) text-s03 FOR FIELD p_file.
  PARAMETERS: p_file TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_survey.
*  SELECTION-SCREEN END OF LINE.

*question file name
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s10 FOR FIELD p_quest.
  PARAMETERS: p_quest TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_quest.
*  SELECTION-SCREEN END OF LINE.

*answer file name.
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s19 FOR FIELD p_answ.
  PARAMETERS: p_answ TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_answ.
*  SELECTION-SCREEN END OF LINE.

* FOR HEDER LOG FILE NAME
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s04 FOR FIELD p_log1.
  PARAMETERS: p_log1  TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_log_head.
*  SELECTION-SCREEN END OF LINE.

* FOR SURVEY LOG FILE NAME
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s88 FOR FIELD p_log2.
  PARAMETERS: p_log2  TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_log_survey.
*  SELECTION-SCREEN END OF LINE.

* FOR QUESTUION LOG FILE NAME
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s89 FOR FIELD p_log3.
  PARAMETERS: p_log3  TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_log_quest.
*  SELECTION-SCREEN END OF LINE.

* FOR ANSWER LOG FILE NAME
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(27) text-s90 FOR FIELD p_log4.
  PARAMETERS: p_log4  TYPE filename-fileintern OBLIGATORY DEFAULT ca_file_log_answ.
*  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK b3.

*END OF FILENAME PARAMETERS

* START FOR OTHER PARAMETERS
  SELECTION-SCREEN BEGIN OF BLOCK b4.
*  WITH FRAME TITLE text-012.

* FOR PACKAGE
*  SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 3(22) text-s08 FOR FIELD p_pack.
  PARAMETERS: p_pack TYPE i OBLIGATORY DEFAULT 400.
*  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b4.
* END OF OTHER PARAMETERS

  SELECTION-SCREEN END OF BLOCK b1.

----------------------------------------------------------------------------------
Extracted by Mass Download version 1.5.5 - E.G.Mellodew. 1998-2020. Sap Release 740
