//--------------------------------------------------------------------------------
//   PROJECT : Traffic Steering - Inbound Server - v 1.11
//--------------------------------------------------------------------------------
//
//   File Name   : tfsin.c
//
//   Created     : 01-09-2004
//
//   Last fix	 : 29-11-2004
//                 15-04-2004 Add TCAP_END / TCAP-CONTINUE management: to do relay
//                 07-09-2005 Add EVT manage
//				   25-11-2005 Add VLR CC and MGT external parameters
//				   13-01-2006 Add memory list of VLR GT
//				   03-03-2006 Link with FRAMEWORK $dsmscm.fwaobj
//				   10-04-2006 CPU Request sending request to GTT and TFS Manager
//				   23-05-2007 TCAP-ABORT managed
//							  Bug Fixed: break in the switch
//				   02-10-2008 Added GT originator control for GPRS Location Update
//				   15-10-2008 Link with FRAMEWORK C and code optimizing
//				   15-02-2010 Added statistic counters idx 89,90,91 and 92
//				   10-06-2010 Bug fixed: allow VPC
//				   15-03-2011 Added new field c_tcap_map_errorcode into gtt and ts IPC structures
//				   22-03-2011 Added other MAP Error management
//				   01-07-2011 Recompiled for KTSTEA07
//				   28-06-2012 Deployed KTSTEACE ( to be include in KTSTEA08 )
//								- optimized input parameters
//								- Added SSN configuration
//				   30-08-2012 Managed MGT len greater than 16  ( routing SCCP max len 32 - MGT max len 30 )
//							  Relaying msg, internal routing managed: Changes to stop checking if the local point code is available, to overcome erroneous retcode from L_SS7_PC_STATUS
//				   04-09-2012 Added IMSI into ts IPC struct
//				   20-09-2012 Bug Fixed EVT_MANAGER - Fixed the maximum number of events generated by TFS MAP i/f
//													  in a given period of time in order to respect the value
// 													  configured as NBR-ALERT-MSG and/or INTERVAL-ALERT-MSG-TIME parameters
//				   09-10-2012 SSN check feature has been suppressed for KDDI
//				   28-11-2012 Bug Fixed: The frames TCAP-CONTINUE,ABORT and END are relayed correctly by RELAY-SERVER
//									     necessary to manage the wrong traffic coming from national core network
//				   19-12-2012 Recompiled for A08.01
//				   10-05-2013 Bug Fixed 3879 KTSTEACP: resolved management of UL GSm V1 with SSN 16 - In this case the FWork came out a Map Version 4 like for INAP-CS1 due to the customized SSN for KDDI
//				   31-05-2013 Recompiled for A08.02 - due to adding of LTE i/f
//				   10-09-2013 Bug Fixed 3987: - SCCP Calling Party Address Digits Number with length equal to zero
//											  - UDTS Header Decoding Information:
//													the decoding of UDTS messages with Return Cause field
//													size longer than 50 bytes generated a stack overflow
//				   13-09-2013 Recompiled for A08.02 it has been included the bug fix KTSTEACR
//				   02-07-2014 RVU 09.00
//							   - Added Roaming Unbundling management
//				   			   - Added Dual IMSI management: Relaying of LU GSM/GPRS
//								 with Routing Indicator - routing on GT
//				   13-04-2015 KTSTEADD - Added anti steering management for LU GSm/GPrs with SCCP CdPA NPI E.164(GT) instead of E.214 (MGT)
//				   14-10-2015 KTSTEADH - Bug fixing wrong invoke id returned towards vlr/sgsn for steering case
//				   23-03-2016 KTSTEADK - Bug fix ErrCmp SystemFailure Network Resource MAP V3
//				   15-05-2017 KTSTEADQ - HLR on DLA(Down Low Adjust) architecture, FAI(Flexible Allocation of IMSI) activation
//				   29-03-2018 KTSTEADV - Flexible Allocation of IMSI (FAI) - Management of GSM LU/GPRS LU and SCCP CdPA ITU E.164
//
//---------------------------------------------------------------------------------
//
//	 Last change  : 29-03-2018
//
//---------------------------------------------------------------------------------
//   Description
//   -----------
//
//---------------------------------------------------------------------------------
//   Functions
//   ---------
//---------------------------------------------------------------------------------
//---------------------< Include files >-------------------------------------------


#pragma nolist
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <memory.h>
#include <string.h>
#include <strings.h>
#include <time.h>
#include <ctype.h>
#include <tal.h>
#include <unistd.h>
#include <p2system.p2apdfh>
#include <erainc.ccpy>
#include <cssinc.cext>    
#include <cextdecs.h (DELAY,PROCESSHANDLE_GETMINE_,PROCESSHANDLE_DECOMPOSE_,JULIANTIMESTAMP)>
#include <fwlbdf.h>
#include <fwroute.h>
#include <fwdef.h>
#include <fwutlx.h>
#include <fwstatl.h>
#include <mapinv.h>
#include <sspevt.h>
#include <ssplog.h>
#include <sspfunc.h>
#include <sspstat.h>
#include "tfsin.h"
#include "tfsipc.h"
#include "tfsdef.h"
#include "tfsdb.h"
#include "tfsfunc.h"
#include "ipcfunc.h"
#include "gsmdef.h"
#include "tfsevt.h"
#include "tfsstat.h"
#include "lu.h"
#pragma list

//---------------------< Definitions >-----------------------------------------

#if (_TNS_E_TARGET)
T0000H06_21JUN2018_KTSTEA10_01() {};
#elif (_TNS_X_TARGET)
T0000L16_21JUN2018_KTSTEA10_01() {};
#endif

//---------------------< Internal Function Prototypes >----------------------
void Process_Initialization( void );

void GetCallerInfo( char *out_name );

void Msg_print( short i_type );

void ManageTCBegin( fw_route_infod routeinfop,
					transactionId *transaction,
					short i_map_vers,
                    dialogueStuff *dialogue,
                    fw_sel_inparsed selp,
                    short i_nbr_component,
                    char *ac_buff_raw,
                    short i_buff_raw_len );

void ManagedInvoke( fw_route_infod routeinfop,
					transactionId *transaction,
					short i_map_vers,
                    dialogueStuff *dialogue,
                    struct ComponentParameter *cmpnt,
                    char *ac_buff_raw,
                    short i_buff_raw_len );

//void CheckSSN_HLR( short i_op,
//				   short i_ssn );

short LoadParameters( char *ac_PathCfgF,
					  short i_reload );

short ManageProcessUpdateLocationRequest ( fw_route_infod routeinfop,
										   US_Route_Info *route_info,
                                           transactionId *transaction,
                                           struct ComponentParameter *cmpnt,
                                           short i_map_vers,
                                           char *ac_buff_raw,
                                           short i_buff_raw_len,
                                           INS_AddressString *GT_mitt,
                                           short *i_err_sccp_cd );

short Process_Sysmesg_Handler( char *ac_msg );

//---------------------< External Function Prototypes >----------------------
//---------------------< External Variables >--------------------------------
//---------------------< Static and Global Variables >-----------------------
short			i_shutdown;
short			i_timeout_allow_vpc_set;
PREFIX_LIST		cg_prefix_owner_tfs;
PREFIX_LIST		cd_prefix_owner_tfs;
PREFIX_LIST		cg_lu_gprs_whitelist;
VPC_STATUS		vpc_status;
//---------------------------------------------------------------------------
int main( int argc, char **argv )
{
    short				rc;
    short               i_res;
	short				i_err;
    short               event;
    short               mapversion;
    short               nbrcomps;
    short               outbuflen;
    short               mtype;
    short               Stop;
    short               i_allow_all;
	short				i_request_gtt;
	char				ac_mtype[32];
	char				ac_outbuf_hex[513];
    char                *outbuf = NULL;
    fw_route_infod      routeinfop;     // pointer to routing info
    fw_sel_inparsed     p_sel;          // pointer to SEL parsed elements structure
    transactionId       transaction;
    dialogueStuff       dialogue;

    //DELAY(1000);

	Stop		= 0;
    i_shutdown	= 0;
	outbuflen	= 0;
	i_allow_all	= 0;

	i_cg_prefix_owner_tfs_loaded  = 0;
	i_cd_prefix_owner_tfs_loaded  = 0;
	i_cg_lu_gprs_whitelist_loaded = 0;

	i_timeout_allow_vpc_set 	  = 0;
	i_stat_fw_param_loaded  	  = 0;

    Process_Initialization();

    if(i_trace_level > LOG_DEBUG)
    {
    	log_(LOG_DEBUG2,"%s: TS-DATA:[%d] - GTT-DATA:[%d]",
    			__FUNCTION__,
    			sizeof(ts_data),
    			sizeof(gtt_data));
    }

    if( Load_Prefix_List( ac_cg_prefix_list_owner_tfs,
                          &cg_prefix_owner_tfs ) )
    {
    	Stop = 1;

    	EVT_manage( EVTN_LOAD_CG_PREFIX_LIST_OWNER_TFS_ERROR,
					0,
					0,
					'A',
					"Loading CG PREFIX OWNER TFS Err" );

		log_( LOG_ERROR,"Loading CG PREFIX OWNER TFS Err - [%s]",ac_cg_prefix_list_owner_tfs);
	}
	else
	{
		i_cg_prefix_owner_tfs_loaded = 1;

		EVT_manage( EVTN_LOAD_CG_PREFIX_LIST_OWNER_TFS_OK,
					0,
					0,
					'N',
					"Loading CG PREFIX OWNER TFS Ok" );


		log_( LOG_INFO,"Loading CG PREFIX OWNER TFS successfully - [%s]",ac_cg_prefix_list_owner_tfs);
	}

    if( !Stop )
    {
		if( Load_Prefix_List( ac_cd_prefix_list_owner_tfs,
							  &cd_prefix_owner_tfs ) )
		{
			Stop = 1;

			EVT_manage( EVTN_LOAD_CD_PREFIX_LIST_OWNER_TFS_ERROR,
						0,
						0,
						'A',
						"Loading CD PREF. OWNER TFS Err" );

			log_( LOG_ERROR,"Loading CD PREFIX OWNER TFS Err - [%s]",ac_cd_prefix_list_owner_tfs);
		}
		else
		{
			i_cd_prefix_owner_tfs_loaded = 1;

			EVT_manage( EVTN_LOAD_CD_PREFIX_LIST_OWNER_TFS_OK,
						0,
						0,
						'N',
						"Loading CD PREFIX OWNER TFS Ok" );


			log_( LOG_INFO,"Loading CD PREFIX OWNER TFS successfully - [%s]",ac_cd_prefix_list_owner_tfs);
		}

		if( !Stop )
		{
			if( Load_Prefix_List( ac_cg_lu_gprs_whitelist,
								  &cg_lu_gprs_whitelist ) )
			{
				Stop = 1;

				EVT_manage( EVTN_LOAD_LU_GPRS_WL_ERROR,
							0,
							0,
							'A',
							"Loading LU GPRS WHLIST Err" );

				log_( LOG_ERROR,"Loading LU GPRS WHLIST Err - [%s]",ac_cg_lu_gprs_whitelist);
			}
			else
			{
				i_cg_lu_gprs_whitelist_loaded = 1;

				EVT_manage( EVTN_LOAD_LU_GPRS_WL_OK,
							0,
							0,
							'A',
							"Loading LU GPRS WHLIST Ok" );


				log_( LOG_INFO,"Loading LU GPRS WHLIST successfully - [%s]",ac_cg_lu_gprs_whitelist);
			}
		}
    }

	if( !Stop )
	{
		// Set timer for bump stat
		if( SetTimerBump_(l_stat_bump_interval,TAG_BUMP ))
		{
			EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
						0,
						i_interval_time,
						'A',
						"SIGNALTIMEOUT_() Err. - Bump Stat" );
		}

		if(SIGNALTIMEOUT_( (long)(l_timeout_reload + (long)(30*(long)(JULIANTIMESTAMP(0)%100))),
							0,
							TAG_RELOAD_PARAM ) )
		{
			EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
						0,
						i_interval_time,
						'A',
						"SIGNALTIMEOUT_() Err. - Reload Parameters" );
		}
	}

    // Main Loop
    while ( !Stop )
    {
        rc = FW2_TCAP_Receive ( &event, &mtype,
                                &mapversion, &nbrcomps,
                                &routeinfop, &p_sel,
                                &transaction, &outbuf,
                                &outbuflen, &dialogue );

		log_(LOG_DEBUG2,"%s: FW2_TCAP_Receive : RC[%d] - RX Buffer len[%d]",
				__FUNCTION__,
				rc,
				outbuflen);

        if ( rc == FW_RCV_OK )
        {
            switch ( event )
            {
                case ( FW_RCV_NORMAL_MAP_TCAP ):
                {
					i_request_gtt = 0;

                    switch ( mtype )
                    {
                        case FW_RCV_TC_BEGIN:
                        {
                            AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_MSG_REC);
                            AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_BEGIN_REC);

                            if( nbrcomps > 0 )
                            {
								log_(LOG_DEBUG2,"%s: RX TCAP-BEGIN with [%d] components",
										__FUNCTION__,
										nbrcomps);

                                ManageTCBegin( routeinfop,
                                               &transaction,
                                               mapversion,
                                               &dialogue,
                                               p_sel,
                                               nbrcomps,
                                               outbuf,
                                               outbuflen );
                            }
                            else
                            {
                                i_request_gtt = 1;

								sprintf(ac_mtype,"%s","TCAP-BEGIN WITHOUT COMP.");

								log_(LOG_ERROR,"RX %s - Sending request to GTT for relaying",ac_mtype);

								if(i_trace_level > LOG_DEBUG)
								{
									memset(ac_outbuf_hex,0x00, sizeof(ac_outbuf_hex));
									Asc2Hex((unsigned char *)outbuf,
											 ac_outbuf_hex,
											 outbuflen);

									log_(LOG_DEBUG2,"%s: %s msg rec. - [%s] - [%d]",
											__FUNCTION__,
											ac_mtype,
											ac_outbuf_hex,
											outbuflen);
								}
                            }

                            break;
                        }

                        case FW_RCV_TC_CONTINUE:
						{
							i_request_gtt  = 1;

							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_MSG_REC);
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_CONTINUE_REC);

							sprintf(ac_mtype,"%s","TCAP-CONTINUE");

							log_(LOG_DEBUG2,"%s: RX %s - Sending request to GTT for relaying",
									__FUNCTION__,
									ac_mtype);

							if(i_trace_level > LOG_DEBUG)
							{
								memset(ac_outbuf_hex,0x00, sizeof(ac_outbuf_hex));
								Asc2Hex((unsigned char *)outbuf,
										ac_outbuf_hex,
										outbuflen);

								log_(LOG_DEBUG2,"%s: %s msg rec. - [%s] - [%d]",
										__FUNCTION__,
										ac_mtype,
										ac_outbuf_hex,
										outbuflen);
							}

							break;
						}

                        case FW_RCV_TC_END:
						{
							i_request_gtt  = 1;

							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_MSG_REC);
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_END_REC);

							sprintf(ac_mtype,"%s","TCAP-END");

							log_(LOG_DEBUG2,"%s: RX %s - Sending request to GTT for relaying",
									__FUNCTION__,
									ac_mtype);

							if(i_trace_level > LOG_DEBUG)
							{
								memset(ac_outbuf_hex,0x00, sizeof(ac_outbuf_hex));
								Asc2Hex((unsigned char *)outbuf,
										ac_outbuf_hex,
										outbuflen);

								log_(LOG_DEBUG2,"%s: %s msg rec. - [%s] - [%d]",
										__FUNCTION__,
										ac_mtype,
										ac_outbuf_hex,
										outbuflen);
							}

							break;
						}

						case FW_RCV_TC_ABORT:
                        {
							i_request_gtt  = 1;

							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_MSG_REC);
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ABORT_REC);

							sprintf(ac_mtype,"%s","TCAP-ABORT");

							log_(LOG_DEBUG2,"%s: RX %s - Sending request to GTT for relaying",
									__FUNCTION__,
									ac_mtype);

							if(i_trace_level > LOG_DEBUG)
							{
								memset(ac_outbuf_hex,0x00, sizeof(ac_outbuf_hex));
								Asc2Hex((unsigned char *)outbuf,
										ac_outbuf_hex,
										outbuflen);

								log_(LOG_DEBUG2,"%s: %s msg rec. - [%s] - [%d]",
										__FUNCTION__,
										ac_mtype,
										ac_outbuf_hex,
										outbuflen);
							}
                           
							break;
                        }

                        case FW_RCV_TC_UNKNOWN:
                        {
                            EVT_manage( EVTN_TCAP_OPCODE_UNKNOWN,
										0,
										i_interval_time,
										'A',
										"TCAP opcode[%d] unknown",
										mtype );

                            log_(LOG_ERROR,"RX unknown TCAP opcode[%d]",mtype);

                            break;
                        }

                        default:
                        {
                            EVT_manage( EVTN_FW_OPCODE_UNKNOWN,
										0,
										i_interval_time,
										'A',
										"FW opcode[%d] unknown",
										mtype );

                            log_(LOG_WARNING,"RX unknown FW opcode[%d]",mtype);

                            break;
                        }
                    } // switch (mtype)
					
					if( i_request_gtt )
					{
						P2_MTS_TAG_DEF			mts_addr_GTT;
						P2_MTS_TAG_DEF			mts_addr_RESP;

                        memset(&mts_addr_GTT,0x00, sizeof(P2_MTS_TAG_DEF));
                        memset(&mts_addr_RESP,0x00, sizeof(P2_MTS_TAG_DEF));

                        mts_addr_GTT.task_id        = i_taskid_gtt;
                        mts_addr_GTT.server_class   = i_serverclass_gtt;
                        mts_addr_GTT.cpu            = 0;

                        mts_addr_RESP.task_id       = i_taskid_relay;
                        mts_addr_RESP.server_class  = i_serverclass_relay;
                        mts_addr_RESP.cpu           = i_my_cpu;

                        // sent to GTT
                        i_res = Sent_Request_to_GTT( &mts_addr_GTT,
                                                     &mts_addr_RESP,
                                                     routeinfop,
                                                     &transaction,
                                                     mapversion,
                                                     0x00, // No Map version requested for relaying
                                                     outbuf,
                                                     outbuflen,
                                                     MAPIN_GTT_RELAY,
                                                     i_my_cpu,
                                                     RELAY_REQ,
													 NO_MAP_ERROR_CODE,
													 1,
													 0,
													 0,
													 CHECK_SCCP_CD_ADDRESS_PREFIX,
													 "---",
													 &cg_prefix_owner_tfs,
													 &cd_prefix_owner_tfs );

                        if( i_res )
                        {
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GTT_REQ_KO);

							log_( LOG_ERROR,"Err.[%d] - Sending Request to GTTS[T:%d;S:%d] - [%s]",
										i_res,
										i_taskid_gtt,
										i_serverclass_gtt,
										ac_mtype );

                            if( i_res == -1 ||
								i_res == -3 )
							{
                                i_shutdown = 1;
							}
							else
							{
								US_Route_Info	routeReadable;

								i_err =	MTP3SCCP_DecodeRoutingInfo( routeinfop,
																	&routeReadable );

								if(!i_err)
									LogRouteInfo( &routeReadable,LOG_WARNING,ac_mtype );
								else
									log_(LOG_ERROR,"Err.[%d] bad routing",i_err);
							}
                        }
                        else
						{
                            AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GTT_REQ_OK);

                            if(i_trace_level > LOG_DEBUG)
                            	log_(LOG_DEBUG2,"%s: - Request sent to GTTS successfully for relaying -",__FUNCTION__);
						}
					}

                    break;
                }

				case FW_RCV_UDTS_MSG:
				{
					memset(ac_outbuf_hex,0x00, sizeof(ac_outbuf_hex));

					Asc2Hex((unsigned char *)outbuf,
							ac_outbuf_hex,
							outbuflen);

					composeUDTSHeaderInfo( ac_outbuf_hex,
										   outbuflen,
										   routeinfop->aggr );

					break;
				}

                case FW_RCV_COMMAND:
                case FW_RCV_PROCESS_SIGNALTIMEOUT:
                {
                    Stop = Process_Sysmesg_Handler( outbuf );

                    break;
                }

                case FW_RCV_SHUTDOWN_REQUEST:
                {
                	log_(LOG_DEBUG2,"%s: RX FW_RCV_SHUTDOWN_REQUEST event",__FUNCTION__);

                	Stop = 1;

                    break;
                }

                case FW_RCV_CONTEXT_SIGNALTIMEOUT:
                {
               		log_(LOG_DEBUG2,"%s: RX FW_RCV_CONTEXT_SIGNALTIMEOUT event",__FUNCTION__);

                    break;
                }

                case FW_RCV_OTHER_MSG:
				{
					log_(LOG_DEBUG2,"%s: RX FW_RCV_OTHER_MSG event - Msg discarded",__FUNCTION__);

					break;
				}

                default:
                {
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_UNKNOWN_FW_EVENT_REC);
                    
                    EVT_manage( EVTN_FW_EVENT_UNKNOWN,
								0,
								i_interval_time,
								'A',
								"RX unknown framework event[%d] - Msg discarded",
								event );

                    log_(LOG_WARNING,"RX unknown framework event[%d] - Msg discarded",event);

                    break;
                }
            }    // switch (event)

            if( i_shutdown &&
            	(i_internal_routing_strategy == NO_INTERNAL_ROUTING_STRATEGY) &&
            	vpc_status.i_vpc )
            {
                // shutdown TGDS Virtual Point Code
                i_shutdown  = 0;
                i_allow_all = 0;

				vpc_status.i_mode = VPC_DOWN;

				if( !(i_res = VPC_Status( &vpc_status )) )
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_OK);

					EVT_manage( EVTN_PROHIBIT_VPC_OK,
								0,
								i_interval_time,
								'A',
								"SHUTDOWN VPC[%d] OK",
								vpc_status.i_vpc );

					log_(LOG_WARNING,"SHUTDOWN VPC[%d] OK", vpc_status.i_vpc);

					i_allow_all++;
				}
				else
				{
					if(i_res != P2_SS7_ALREADY_PROHIB)
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_KO);

						EVT_manage( EVTN_PROHIBIT_VPC_KO,
									0,
									i_interval_time,
									'A',
									"SHUTDOWN VPC[%d] failed - Err.[%d]",
									vpc_status.i_vpc,
								 	i_res );

						log_(LOG_ERROR,"SHUTDOWN VPC[%d] failed - Err.[%d]",
								vpc_status.i_vpc,
								i_res);
					}
					else
					{
						if(!i_timeout_allow_vpc_set)
						{
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_OK);

							EVT_manage( EVTN_PROHIBIT_VPC_OK,
										0,
										i_interval_time,
										'A',
										"VPC[%d] already down",
										vpc_status.i_vpc );

							log_(LOG_WARNING,"VPC[%d] already down",vpc_status.i_vpc);
						}

						i_allow_all++;
					}
				}

                if( i_allow_all )
                {
                    if( i_auto_allow_vpc && !i_timeout_allow_vpc_set )
					{
						if(!SIGNALTIMEOUT_(l_timeout_allow_vpc,0,TAG_ALLOW_VPC))
							i_timeout_allow_vpc_set = 1;
						else
						{
							EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
										0,
										i_interval_time,
										'A',
										"SIGNALTIMEOUT_ Err. - Allow VPC" );
						}
					}
                }
            }
        }    // if (rc == FW_RCV_OK)
        else
        {
            EVT_manage( EVTN_FW_ERROR,
						0,
						i_interval_time,
						'A',
						"Err.[%d] - FW2_TCAP_Receive()",
						rc );

            log_(LOG_ERROR,"Err.[%d] - FW2_TCAP_Receive()",rc);
        }
    }

    i_res = (short)BumpStat();

    if( !i_res )
        log_( LOG_INFO, "Bump Statistics" );
    else
    {
        EVT_manage( EVTN_BUMP_ERROR,
					0,
					0,
					'A',
					"Err.[%d] - BumpStat()",
					i_res );

        log_( LOG_ERROR, "Err.[%d] - BumpStat()",i_res);
    }

    if( i_cg_prefix_owner_tfs_loaded )
    	Unload_Prefix_List(&cg_prefix_owner_tfs);

	if( i_cd_prefix_owner_tfs_loaded )
		Unload_Prefix_List(&cd_prefix_owner_tfs);

	if( i_cg_lu_gprs_whitelist_loaded )
		Unload_Prefix_List(&cg_lu_gprs_whitelist);

    Msg_print( _STOP_ );

    log_close();

    return 0;
}

//
// Manage system message
//
short Process_Sysmesg_Handler( char *ac_msg )
{
    short            i_res;
    short            i_ret = 0;
    short            i_allow_all;
    long			 i_tmp_reload_param;
    PREFIX_LIST		 cg_prefix_owner_tfs_tmp;
    PREFIX_LIST		 cd_prefix_owner_tfs_tmp;
    PREFIX_LIST		 cg_lu_gprs_whitelist_tmp;
    IO_SYS_TIMEOUT   *signal;
    SYS_COMMAND      *cmd;

	signal = (IO_SYS_TIMEOUT *)ac_msg;

    switch( signal->id )
    {
        case SYS_MSG_TIME_TIMEOUT:
        {
			log_(LOG_DEBUG2,"%s: [SYS_MSG_TIME_TIMEOUT] - Sock[%d] Tag[%ld]",
					__FUNCTION__,
					signal->i_socket,
					signal->l_tag);

            switch ( signal->l_tag )
            {
                case TAG_RELOAD_PARAM:
                {
					if ( checkChgFile( ac_filecfg_oss ) )
					{
						if( !LoadParameters(ac_filecfg,RELOAD) )
						{
							EVT_manage( EVTN_PARAM_MISSING,
										0,
										i_interval_time,
										'A',
										"Missing parameter or fileini opened" );

							log_ (LOG_WARNING, "Reloading parameters failed: missing parameter or fileini opened");
						}
						else
						{
							log_ (LOG_DEBUG2, "%s: Reloading parameters successfully",__FUNCTION__);
						}
					}
					else
					{
						log_ (LOG_DEBUG2, "%s: Reloading parameters not necessary",__FUNCTION__);
					}

					if( i_cg_prefix_owner_tfs_loaded )
					{
						if( Load_Prefix_List( ac_cg_prefix_list_owner_tfs,
											  &cg_prefix_owner_tfs_tmp ) )
						{
							EVT_manage( EVTN_RELOAD_CG_PREFIX_LIST_OWNER_TFS_ERROR,
										0,
										0,
										'A',
										"Reloading CG PREFIX OWNER TFS Err" );

							log_( LOG_ERROR,"Reloading CG PREFIX OWNER TFS Err - [%s]",ac_cg_prefix_list_owner_tfs);
						}
						else
						{
							Unload_Prefix_List(&cg_prefix_owner_tfs);

							cg_prefix_owner_tfs = cg_prefix_owner_tfs_tmp;

							log_( LOG_DEBUG2,"%s: Reloading CG PREFIX OWNER TFS successfully - [%s]",
									__FUNCTION__,
									ac_cg_prefix_list_owner_tfs);
						}
					}

					if( i_cd_prefix_owner_tfs_loaded )
					{
						if( Load_Prefix_List( ac_cd_prefix_list_owner_tfs,
											  &cd_prefix_owner_tfs_tmp ) )
						{
							EVT_manage( EVTN_RELOAD_CD_PREFIX_LIST_OWNER_TFS_ERROR,
										0,
										0,
										'A',
										"Reloading CD PREFIX OWNER TFS Err" );

							log_( LOG_ERROR,"Reloading CD PREFIX OWNER TFS Err - [%s]",ac_cd_prefix_list_owner_tfs);
						}
						else
						{
							Unload_Prefix_List(&cd_prefix_owner_tfs);

							cd_prefix_owner_tfs = cd_prefix_owner_tfs_tmp;

							log_( LOG_DEBUG2,"%s: Reloading CD PREFIX OWNER TFS successfully - [%s]",
									__FUNCTION__,
									ac_cd_prefix_list_owner_tfs);
						}
					}

					if( i_cg_lu_gprs_whitelist_loaded )
					{
						if( Load_Prefix_List( ac_cg_lu_gprs_whitelist,
											  &cg_lu_gprs_whitelist_tmp ) )
						{
							EVT_manage( EVTN_RELOAD_LU_GPRS_WL_ERROR,
										0,
										0,
										'A',
										"Reloading LU GPRS WHLIST Err" );

							log_( LOG_ERROR,"Reloading LU GPRS WHLIST Err - [%s]",ac_cg_lu_gprs_whitelist);
						}
						else
						{
							Unload_Prefix_List(&cg_lu_gprs_whitelist);

							cg_lu_gprs_whitelist = cg_lu_gprs_whitelist_tmp;

							log_( LOG_DEBUG2,"%s: Reloading LU GPRS WHLIST successfully - [%s]",
									__FUNCTION__,
									ac_cg_lu_gprs_whitelist);
						}
					}

					if(SIGNALTIMEOUT_( (long)(l_timeout_reload + (long)(30*(long)(JULIANTIMESTAMP(0)%100))),
										0,
										TAG_RELOAD_PARAM ) )
					{
						EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
									0,
									i_interval_time,
									'A',
									"SIGNALTIMEOUT_() Err. - Reload Parameters" );
					}

                    break;
                }

                case TAG_BUMP:
                {
                    // Bump
                    i_res = (short)BumpStat();

                    if( !i_res )
                    {
                   		log_( LOG_DEBUG2, "%s: Bump Statistics",__FUNCTION__ );
                    }
                    else
                    {
                        EVT_manage( EVTN_BUMP_ERROR,
									0,
									i_interval_time,
									'A',
									"Err.[%d] - BumpStat()",
									i_res );

                        log_(LOG_ERROR, "Err.[%d] - BumpStat()",i_res);
                    }

                    if( SetTimerBump_(l_stat_bump_interval,TAG_BUMP ))
					{
						EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
									0,
									i_interval_time,
									'A',
									"SIGNALTIMEOUT_() Err. - BumpStat()" );
					}

                    break;
                }

                case TAG_ALLOW_VPC:
                {
                    i_shutdown  = 0;
                    i_allow_all = 0;
					i_timeout_allow_vpc_set = 0;

					vpc_status.i_mode = VPC_UP;

					if( !(i_res = VPC_Status( &vpc_status )) )
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ALLOW_PC_REQ_OK);

						EVT_manage( EVTN_ALLOW_VPC_OK,
									0,
									i_interval_time,
									'A',
									"VPC[%d] is alive",
									vpc_status.i_vpc );

						log_(LOG_DEBUG2,"%s: VPC[%d] is alive",
								__FUNCTION__,
								vpc_status.i_vpc);

						i_allow_all++;
					}
					else
					{
						if(i_res == P2_SS7_ALREADY_ALLOWD)
						{
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ALLOW_PC_REQ_OK);

							EVT_manage( EVTN_ALLOW_VPC_OK,
										0,
										i_interval_time,
										'A',
										"VPC[%d] is already alive",
										vpc_status.i_vpc );

							log_(LOG_DEBUG2,"%s: VPC[%d] is already alive",
									__FUNCTION__,
									vpc_status.i_vpc);

							i_allow_all++;
						}
						else
						{
							AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ALLOW_PC_REQ_KO);

							EVT_manage( EVTN_ALLOW_VPC_OK,
										0,
										i_interval_time,
										'A',
										"Allow VPC[%d] failed - Err.[%d] - retry",
										 vpc_status.i_vpc,
										 i_res );


							log_(LOG_ERROR,"VPC[%d] is down - Err.[%d] - retry",
										vpc_status.i_vpc,
										i_res);
						}
					}

                    if( i_allow_all )
                    {
                        if( i_auto_allow_vpc )
						{
                            if(!SIGNALTIMEOUT_(l_timeout_allow_vpc,0,TAG_ALLOW_VPC))
								i_timeout_allow_vpc_set = 1;
                            else
                            {
                            	EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
											0,
											i_interval_time,
											'A',
											"SIGNALTIMEOUT_() Err. - Allow VPC" );
                            }
						}
                    }

                    break;
                }
            }

            break;
        }

        case SYS_MSG_COMMAND:
        {
            cmd = (SYS_COMMAND *)ac_msg;
			cmd->ac_cmd[cmd->i_cnt] = 0;

			if( !strcmp(cmd->ac_cmd,"PARAMREFRESH") )
			{
				log_(LOG_DEBUG2,"%s: RX PARAMREFRESH request",__FUNCTION__);

				i_tmp_reload_param = (long)(JULIANTIMESTAMP(0)%100);

				if( i_tmp_reload_param < 3 )
					i_tmp_reload_param = 3;

				// shifting JULIANTIMESTAMP(0) + [3 - 33"]
				if( SIGNALTIMEOUT_((long)( 30 * i_tmp_reload_param ),0,TAG_RELOAD_PARAM) )
				{
					EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
								0,
								0,
								'A',
								"SIGNALTIMEOUT_() Err. - PARAMREFRESH" );

					log_(LOG_ERROR,"SIGNALTIMEOUT_() Err. - Reloading parameters" );
				}
				else
				{
					EVT_manage( EVTN_CMD_REFRESH_PARAM_OK,
								0,
								0,
								'N',
								"RX PARAMREFRESH request" );
				}
			}
			else
			{
				EVT_manage( EVTN_CMD_UNHANDLE,
							0,
							0,
							'A',
							"RX unhandle cmd[%s] request",
							cmd->ac_cmd );

				log_(LOG_ERROR,"RX unhandle cmd[%s] request",cmd->ac_cmd);
			}

            break;
        }

        case SYS_MSG_STOP_1:
        case SYS_MSG_STOP_2:
        {
            i_ret = 1;

            break;
        }
    }

    return i_ret;

} // End Of Procedure

//
// Manage TCAP Begin
//
void ManageTCBegin( fw_route_infod routeinfop,
                    transactionId *transaction,
                    short i_map_version,
                    dialogueStuff *dialogue,
                    fw_sel_inparsed selp,
                    short number_of_components,
                    char *ac_msg_raw,
                    short i_msg_raw_len )
{
    short   i_found             = 0;
    int     i_order             = 0;
    struct  ComponentParameter   cmpnt;

    do
    {
        memset(&cmpnt,0x00, sizeof(cmpnt));
        BuildComponentParameter( selp,
                                 i_order,
                                 &cmpnt );

        switch( cmpnt.component_type )
        {
            case 0x01:      // Invoke
            {
                AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_INVOKE);

                ManagedInvoke( routeinfop,
                               transaction,
                               i_map_version,
                               dialogue,
                               &cmpnt,
                               ac_msg_raw,
                               i_msg_raw_len );

                i_found = 1;

                break;
            }

            case 0x02:      // Return Result
            case 0x03:      // Return Error
            case 0x04:      // Reject
            case 0x07:      // Return Result Not Last
            {
                AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_NOT_INVOKE);

                log_(LOG_WARNING,"%s: RX unsupported component type: [%d]",
                        __FUNCTION__,
                		cmpnt.component_type);

                break;
            }

            default:
            {
                AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_UNKNOWN_COMP);

                log_(LOG_WARNING,"%s: RX unrecognized component type: [%d]",
                		__FUNCTION__,
                        cmpnt.component_type);

                break;
            }
        }

        i_order++;
    } while( !i_found || i_order < number_of_components - 1 );
}

//
// Manage Invoke and it does relay request
//
void ManagedInvoke( fw_route_infod routeinfop,
                    transactionId *transaction,
                    short i_map_vers,
                    dialogueStuff *dialogue,
                    struct ComponentParameter *cmpnt,
                    char *ac_raw,
                    short i_raw_len )
{
    short           	i_err_sccp_cg;
    short				i_err_sccp_cd;
    short				i_err;
    short           	i_cg_national;
    short           	i_relay;
    short           	i_allow_all;
	short				i_log_routeinfo = 0;
    char            	ac_GT_mitt[MAX_INS_STRING_LENGTH +1];
    char            	ac_GT_dest[MAX_INS_STRING_LENGTH +1];
	char				ac_txt[255];
    US_Route_Info   	routeReadable;
	INS_AddressString	GT_mitt;

    i_err = MTP3SCCP_DecodeRoutingInfo( routeinfop,
										&routeReadable );

	if( !i_err )
	{
		if( routeReadable.cd_addr.gt.address.length > MAX_E214_NBR_OF_DIGIT  )
		{
			log_(LOG_ERROR,"Err. decoding SCCP routing - Unsupported SCCP CD len[%d digits] - Msg discarded",
						routeReadable.cd_addr.gt.address.length);
		}
		else
		{
			i_cg_national = 0;
			i_relay 	  = 0;
			ac_txt[0]	  = '\0';

			memset( ac_GT_mitt,
					0x00,
					sizeof(ac_GT_mitt) );

			memset( ac_GT_dest,
					0x00,
					sizeof(ac_GT_dest) );

			strcpy(ac_GT_mitt,"---");

			memcpy( ac_GT_dest,
					routeReadable.cd_addr.gt.address.value,
					routeReadable.cd_addr.gt.address.length );

			// ********************** for Statistic only **********************************************
//			CheckSSN_HLR( cmpnt->operationCode,
//						  routeReadable.cd_addr.ssn );

			GT_mitt.address.length = 0;

			i_err_sccp_cg = Check_SCCP_CG_Addr( &routeReadable,
												&GT_mitt,
												&cg_prefix_owner_tfs );

			switch( i_err_sccp_cg )
			{
				case SCCP_OK:
				{
					memcpy( ac_GT_mitt,
							GT_mitt.address.value,
							GT_mitt.address.length );

					log_(LOG_DEBUG,"TC-BEGIN: SCCP CG [%s] correct",ac_GT_mitt);

					break;
				}

				case ERR_SCCP_CG_OWNER_TFS:
				{
					i_log_routeinfo = 1;
					i_cg_national 	= 1;

					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_CALLING_NATIONAL_GT);

					memcpy( ac_GT_mitt,
							GT_mitt.address.value,
							GT_mitt.address.length );

					strcpy(ac_txt,"TC-BEGIN: SCCP CG OWNER TFS");

					break;
				}

	//			case ERR_SCCP_CG_WRONG_NPI:
	//			{
	//				i_log_routeinfo = 1;
	//				memcpy( ac_GT_mitt,
	//						GT_mitt.address.value,
	//						GT_mitt.address.length );
	//
	//				strcpy(ac_txt,"TC-BEGIN: SCCP CG wrong NPI");
	//
	//				break;
	//			}

				case ERR_SCCP_CG_NATIONAL:
				{
					i_log_routeinfo = 1;
					i_cg_national 	= 1;

					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_CALLING_NATIONAL_GT);

					memcpy( ac_GT_mitt,
							GT_mitt.address.value,
							GT_mitt.address.length );

					strcpy(ac_txt,"TC-BEGIN: SCCP CG indicator present and NAI national");

					break;
				}

				case ERR_SCCP_CG_NOT_PRESENT:
				{
					if( routeReadable.cg_addr.Addr_ind.pc_ind == '1' )
					{
						i_log_routeinfo = 1;

						strcpy(ac_txt,"TC-BEGIN: SCCP CG indicator absent and PC indicator present");
					}

					if( routeReadable.cg_addr.Addr_ind.pc_ind == '0' )
					{
						i_log_routeinfo = 1;

						strcpy(ac_txt,"TC-BEGIN: SCCP CG and SCCP PC indicator absent");
					}

					break;
				}

				case ERR_SCCP_CG_LEN_ZERO:
				{
					i_log_routeinfo = 1;

					strcpy(ac_txt,"TC-BEGIN: SCCP CG indicator present and CG Address length = 0");

					break;
				}
			}

			if( i_log_routeinfo == 1 )
			{
				switch ( cmpnt->operationCode )
				{
					case UpdateGSMLocation_Request_OperationCode:
					case UpdateGPRSLocation_Request_OperationCode:
					{
						if( i_trace_level >= LOG_WARNING )
						{
							LogRouteInfo( &routeReadable,
										  LOG_WARNING,
										  ac_txt );
						}

						break;
					}

					default:
					{
						if( i_trace_level >= LOG_DEBUG )
						{
							LogRouteInfo( &routeReadable,
										  LOG_DEBUG,
										  ac_txt );
						}

						break;
					}
				}
			}

			// Check if MGT is owner
			if( !Find_Prefix( &cd_prefix_owner_tfs,
							  (char *)ac_GT_dest ) )
			{
				// Unknown MGT
				AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_MGT_UNKNOWN);
			}

			// Set MSC stat
			SetMSCStat( routeReadable.mtp3_opc, TOT_MSC_BEGIN_REC );

			// ****************************************************************************************

			switch ( cmpnt->operationCode )
			{
				case UpdateGSMLocation_Request_OperationCode:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GSM_UPDATE_LOCATION_REC);

					if( routeReadable.cd_addr.gt.NumberingPlan == GT_NP_ISDN_TELEPHONY_E164 )
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_LU_GSM_E164_REC);
					}

					// TOT LU GSM with SCCP CG TFS or NAI National
					if( i_cg_national )
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GSM_NATIONAL_CALLING);

	//				if( i_err_sccp_cg == SCCP_OK )
	//				{
						i_err = ManageProcessUpdateLocationRequest( routeinfop,
																	&routeReadable,
																	transaction,
																	cmpnt,
																	i_map_vers,
																	ac_raw,
																	i_raw_len,
																	&GT_mitt,
																	&i_err_sccp_cd );

						switch( i_err )
						{
							case RELAY:
							{
								i_relay = 1;

								break;
							}

							case NOP:
							{
								log_(LOG_ERROR,"RX GSM LU - Err.[%d] - [Cg=%s:%d] - [Wrong Cd=%s:%d] - No Operation to do",
												i_err_sccp_cd,
												ac_GT_mitt,
												routeReadable.cg_addr.ssn,
												ac_GT_dest,
												routeReadable.cd_addr.ssn);

								break;
							}
						}
	//				}
	//				else
	//				{
	//					i_relay = 1; // Relaying
	//
//						log_(LOG_DEBUG2,"%s: RX GSM LU - [Wrong Cg=%s:%d] - [Cd=%s:%d] - Relaying",
//								__FUNCTION__,
//								ac_GT_mitt,
//								routeReadable.cg_addr.ssn,
//								ac_GT_dest,
//								routeReadable.cd_addr.ssn);
	//				}

					break;
				}

				case UpdateGPRSLocation_Request_OperationCode:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GPRS_UPDATE_LOCATION_REC);

					if( routeReadable.cd_addr.gt.NumberingPlan == GT_NP_ISDN_TELEPHONY_E164 )
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_LU_GPRS_E164_REC);
					}

					// TOT LU GPRS with SCCP CG TFS or NAI National
					if( i_cg_national )
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GPRS_NATIONAL_CALLING);

	//				if( i_err_sccp_cg == SCCP_OK )
	//				{
						switch( i_manage_GPRS_UpLoc )
						{
							case 0:
							{
								i_relay = 1;

								break;
							}

							case 1:
							{
								log_(LOG_DEBUG,"RX GPRS LU - [Cg=%s:%d] - [Cd=%s:%d] - Checking White List",
												ac_GT_mitt,
												routeReadable.cg_addr.ssn,
												ac_GT_dest,
												routeReadable.cd_addr.ssn);

								if( i_cg_lu_gprs_whitelist_loaded )
								{
									if( Find_Prefix( &cg_lu_gprs_whitelist,
													 ac_GT_mitt ) )
									{
										log_(LOG_DEBUG,"GPRS LU: [Cg=%s:%d] - Steering",
												ac_GT_mitt,
												routeReadable.cg_addr.ssn);
									}
									else
									{
										i_relay = 1;

										log_(LOG_DEBUG,"GPRS LU: [Cg=%s:%d] - Orig. VLR Prefix not found  - Relay",
												ac_GT_mitt,
												routeReadable.cg_addr.ssn);
									}
								}
								else
									i_relay = 0;

								break;
							}

							case 2:
							{
								i_relay = 0; // Always steering requested to TFS Manager

								log_(LOG_DEBUG,"RX GPRS LU - [Cg=%s:%d] - [Cd=%s:%d] - Always steering",
											ac_GT_mitt,
											routeReadable.cg_addr.ssn,
											ac_GT_dest,
											routeReadable.cd_addr.ssn);

								break;
							}

							default:
							{
								i_relay = 1;

								log_(LOG_DEBUG,"RX GPRS LU - [Cg=%s:%d] - [Cd=%s:%d] - Always realying",
												ac_GT_mitt,
												routeReadable.cg_addr.ssn,
												ac_GT_dest,
												routeReadable.cd_addr.ssn);

								break;
							}
						}

						if( !i_relay )
						{
							i_err = ManageProcessUpdateLocationRequest( routeinfop,
																		&routeReadable,
																		transaction,
																		cmpnt,
																		i_map_vers,
																		ac_raw,
																		i_raw_len,
																		&GT_mitt,
																		&i_err_sccp_cd );

							switch( i_err )
							{
								case RELAY:
								{
									i_relay = 1;

									break;
								}

								case NOP:
								{
									log_(LOG_ERROR,"RX GPRS LU - Err.[%d] - [Cg=%s:%d] - [Wrong Cd=%s:%d] - No Operation to do",
														i_err_sccp_cd,
														ac_GT_mitt,
														routeReadable.cg_addr.ssn,
														ac_GT_dest,
														routeReadable.cd_addr.ssn);

									break;
								}
							}
						}
	//				}
	//				else
	//				{
	//					i_relay = 1; // Relay
	//					log_(LOG_DEBUG2,"%s: GPRS Location Update received - [Wrong Cg=%s:%d] - [Cd=%s:%d] - Relaying",
	//							__FUNCTION__,
    //							i_err_sccp_cg,
	//							ac_GT_mitt,
	//							routeReadable.cg_addr.ssn,
	//							ac_GT_dest,
	//							routeReadable.cd_addr.ssn);
	//				}

					break;
				}

				case Parameters_request:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SEND_PARAM_REQ_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX SEND_PARAMETER [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
							__FUNCTION__,
							ac_GT_mitt,
							routeReadable.cg_addr.ssn,
							ac_GT_dest,
							routeReadable.cd_addr.ssn);

					break;
				}

				case Authentication_Request:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SEND_AUTH_INFO_REQ_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX AUTHENTICATION_INFO [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case Restore_Data:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_RESTORE_DATA_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX RESTORE_DATA [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case Ready_For_Short_Message:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_READY_FOR_SM_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX READY_FOR_SM [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case Purge_Mobile_Subscriber:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_PURGE_MOBILE_SUBSCRIBER_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX PURGE_MOBILE_SUBSCRIBER [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case Process_Unstructured_SS_Request:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_PROC_UNSTRUCTURED_SS_REQ_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX UNSTRUCTURED_SS [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case Interogate_SS:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_INTEROGATE_SS_REC);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX SS_INTEROGATE [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case SendRoutingInfo:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SRI);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX SRI [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case SendRoutingInfo_for_SM:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SRI_SM);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX SRI_SM [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case ReportDeliveryStatus:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_RDS);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX REPORT_DELIVERY_STATUS [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case ProcessUnstructuredSSRequested:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_PROC_USS_REQ);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX PROCESS_UNSTRUCURED_SS_REQUEST [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case SendRoutingInfoForLCS:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SRI_LCS);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX SRI_LCS [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case RegisterSS:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_REGISTER_SS);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX REGISTER_SS [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				case EraseSS:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ERASE_SS);

					i_relay = 1;

					log_(LOG_DEBUG2,"%s: RX ERASE_SS [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
								__FUNCTION__,
								ac_GT_mitt,
								routeReadable.cg_addr.ssn,
								ac_GT_dest,
								routeReadable.cd_addr.ssn);

					break;
				}

				default:
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_OTHER_MAP_MSG_REC);

					i_relay = 1;

					log_(LOG_WARNING,"RX other MAP_Op[Op=%d] [Cg=%s:%d] - Relaying",
									cmpnt->operationCode,
									ac_GT_mitt,
									routeReadable.cg_addr.ssn);

					break;
				}
			}

			if( i_relay )
			{
				P2_MTS_TAG_DEF mts_addr_GTT;
				P2_MTS_TAG_DEF mts_addr_RESP;

				memset(&mts_addr_GTT,0x00, sizeof(P2_MTS_TAG_DEF));
				memset(&mts_addr_RESP,0x00, sizeof(P2_MTS_TAG_DEF));

				mts_addr_GTT.task_id        = i_taskid_gtt;
				mts_addr_GTT.server_class   = i_serverclass_gtt;
				mts_addr_GTT.cpu            = 0;

				mts_addr_RESP.task_id       = i_taskid_relay;
				mts_addr_RESP.server_class  = i_serverclass_relay;
				mts_addr_RESP.cpu           = i_my_cpu;

				// sent to GTT
				i_err = Sent_Request_to_GTT( &mts_addr_GTT,
											 &mts_addr_RESP,
											 routeinfop,
											 transaction,
											 i_map_vers,
											 (char)(cmpnt->operationCode),
											 ac_raw,
											 i_raw_len,
											 MAPIN_GTT_RELAY,
											 i_my_cpu,
											 RELAY_REQ,
											 NO_MAP_ERROR_CODE,
											 cmpnt->InvokeID,
											 0,
											 0,
											 CHECK_SCCP_CD_ADDRESS_PREFIX,
											 ac_GT_mitt,
											 &cg_prefix_owner_tfs,
											 &cd_prefix_owner_tfs );

				if( i_err )
				{
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GTT_REQ_KO);

					log_( LOG_ERROR,"Err.[%d] - Sending Request to GTTS[T:%d;S:%d] - TC-BEGIN: Comp.Op.Code[%d]",
								i_err,
								i_taskid_gtt,
								i_serverclass_gtt,
								cmpnt->operationCode );

					if( i_err == -1 ||
						i_err == -3 )
					{
						if( (i_internal_routing_strategy == NO_INTERNAL_ROUTING_STRATEGY) &&
							vpc_status.i_vpc )
						{
							i_shutdown  = 0;
							i_allow_all = 0;

							// shutdown TGDS Point Code
							vpc_status.i_mode = VPC_DOWN;

							if( !(i_err = VPC_Status( &vpc_status )) )
							{
								AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_OK);

								EVT_manage( EVTN_PROHIBIT_VPC_OK,
											0,
											0,
											'A',
											"SHUTDOWN VPC[%d] OK - Cg[%s] - Cd[%s]",
											vpc_status.i_vpc,
											 ac_GT_mitt,
											 ac_GT_dest );

								log_(LOG_WARNING,"SHUTDOWN VPC[%d] OK - Cg[%s] - Cd[%s]",
											vpc_status.i_vpc,
											ac_GT_mitt,
											ac_GT_dest);

								i_allow_all++;
							}
							else
							{
								if(i_err != P2_SS7_ALREADY_PROHIB)
								{
									AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_KO);

									EVT_manage( EVTN_PROHIBIT_VPC_KO,
												0,
												0,
												'A',
												"SHUTDOWN VPC[%d] failed - Err.[%d] - Cg[%s] - Cd[%s]",
												vpc_status.i_vpc,
												ac_GT_mitt,
												ac_GT_dest );

									log_(LOG_ERROR,"SHUTDOWN VPC[%d] failed - Err.[%d] - Cg[%s] - Cd[%s]",
												vpc_status.i_vpc,
												i_err,
												ac_GT_mitt,
												ac_GT_dest);
								}
								else
								{
									if(!i_timeout_allow_vpc_set)
									{
										AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_SHUTDOWN_PC_REQ_OK);

										EVT_manage( EVTN_PROHIBIT_VPC_OK,
													0,
													0,
													'A',
													"VPC[%d] already down",
													vpc_status.i_vpc );

										log_(LOG_WARNING,"VPC[%d] already down",vpc_status.i_vpc);
									}

									i_allow_all++;
								}
							}

							if( i_allow_all )
							{
								if( i_auto_allow_vpc && !i_timeout_allow_vpc_set )
								{
									if(!SIGNALTIMEOUT_(l_timeout_allow_vpc,0,TAG_ALLOW_VPC))
										i_timeout_allow_vpc_set = 1;
									else
									{
										EVT_manage( EVTN_SIGNALTIMEOUT_ERROR,
													0,
													i_interval_time,
													'A',
													"SIGNALTIMEOUT_() Err. - Allow VPC" );
									}
								}
							}
						}
					}
				}
				else
					AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_GTT_REQ_OK);
			}
		}
	}
	else
	{
		log_(LOG_ERROR,"Err.[%d] Decoding routing - Bad routing",i_err);
	}
}

//
// - Manage the UpdateLocation request
// - Steering sent to TS Manager
// - Return code error for relay operation
//      0 - Steering done
//      1 - GTTS requested
//      2 - NOP (No Operation to do)
//
short ManageProcessUpdateLocationRequest ( fw_route_infod routeinfop,
                                           US_Route_Info *route_info,
                                           transactionId *transaction,
                                           struct ComponentParameter *cmpnt,
                                           short i_map_version,
                                           char *ac_raw_mesg,
                                           short i_raw_mesg_len,
                                           INS_AddressString *GT_mitt,
                                           short *i_err_sccp_cd )
{
    short               i_err;
    short				i_op_to_do = RELAY; // Default
    char                ac_mitt[MAX_INS_STRING_LENGTH +1];
    char                ac_dest[MAX_INS_STRING_LENGTH +1];
    char				c_CdPA_NPI_is_E164;
	EXTERNAL_REF		ExternalReference;
    ts_data             tfs_manager;

    memset(&tfs_manager,0x00, sizeof(tfs_manager));
    memset(ac_mitt,0x00, MAX_INS_STRING_LENGTH +1);
    memset(ac_dest,0x00, MAX_INS_STRING_LENGTH +1);

    *i_err_sccp_cd = Check_SCCP_CD_Addr( route_info,
    									 &tfs_manager.MGT_dest,
    									 &c_CdPA_NPI_is_E164,
    									 &cd_prefix_owner_tfs );

    switch( *i_err_sccp_cd )
	{
		case SCCP_OK:
		{
			memcpy( ac_dest,
					tfs_manager.MGT_dest.address.value,
					tfs_manager.MGT_dest.address.length );

			log_(LOG_DEBUG2,"%s: TC-BEGIN: SCCP CD[%s] %s",
					__FUNCTION__,
					ac_dest,
					(c_CdPA_NPI_is_E164 == 0x00?"is correct - NPI[E.214]":"is correct but unexpected NPI[E.164]"));

			i_op_to_do = STEERING;

			break;
		}

		case ERR_SCCP_CD_NOT_OWNER_TFS:
		{
			memcpy( ac_dest,
					tfs_manager.MGT_dest.address.value,
					tfs_manager.MGT_dest.address.length );

			log_(LOG_WARNING,"TC-BEGIN: SCCP CD[%s] NOT OWNER TFS - Relay",ac_dest);

			break;
		}

		case ERR_SCCP_CD_NATIONAL:
		{
			memcpy( ac_dest,
					tfs_manager.MGT_dest.address.value,
					tfs_manager.MGT_dest.address.length );

			log_(LOG_WARNING,"TC-BEGIN: SCCP CD[%s] indicator present and NAI national - Relay",ac_dest);

			break;
		}

		case ERR_SCCP_CD_WRONG_NPI:
		{
			memcpy( ac_dest,
					tfs_manager.MGT_dest.address.value,
					tfs_manager.MGT_dest.address.length );

			log_(LOG_WARNING,"TC-BEGIN: SCCP CD[%s] wrong NPI - Relay",ac_dest);

			break;
		}

		case ERR_SCCP_CD_LEN_ZERO:
		{
			log_(LOG_WARNING,"TC-BEGIN: SCCP CD indicator present but CD is empty - Relay");

			break;
		}

		case ERR_SCCP_CD_NOT_PRESENT:
		{
			log_(LOG_WARNING,"TC-BEGIN: SCCP CD absent - Relay");

			break;
		}
	}

    switch( i_op_to_do  )
    {
        case STEERING:
        {
			memset(&ExternalReference,0x00,sizeof(EXTERNAL_REF));

			//
			// TFS
			//
			tfs_manager.i_tag       = TS_TAG;
			tfs_manager.op_code     = cmpnt->operationCode;
			tfs_manager.ResultType  = 0;
			tfs_manager.ResultCode  = 0;

			//
			// MTS_SEND
			//
			tfs_manager.result_address.choice                           = 0x01;
			tfs_manager.result_address.address.mts_address.task_id      = i_taskid_mapout;
			tfs_manager.result_address.address.mts_address.server_class = i_serverclass_mapout;
			tfs_manager.result_address.address.mts_address.cpu_req		= 1;
			tfs_manager.result_address.address.mts_address.cpu          = i_my_cpu;

			tfs_manager.c_E164 = c_CdPA_NPI_is_E164;

			ExternalReference.i_routeinfo_len = sizeof(FW_Route_Info);
			memcpy( &ExternalReference.routeinfo,
					routeinfop,
					ExternalReference.i_routeinfo_len );

			ExternalReference.out_buff_len = i_raw_mesg_len;

			memcpy( ExternalReference.out_buffer,
					ac_raw_mesg,
					ExternalReference.out_buff_len );

			memcpy( &ExternalReference.ac_transaction,
					(char *)transaction,
					sizeof(ExternalReference.ac_transaction) );

			ExternalReference.c_from        = MAPIN_TS_MAPOUT;
			ExternalReference.c_invoke_id   = cmpnt->InvokeID;

			if( cmpnt->operationCode == UpdateGSMLocation_Request_OperationCode )
			{
				//
				// FRW returns for GSM LU V1 a wrong MAP version INAP-CS1 due to a customized SSN=16 for KDDI only
				//
				if(i_map_version > 3)
					i_map_version = 1;

			}

			ExternalReference.c_map_version = (char)i_map_version;
			ExternalReference.c_orig_cpu    = (char)i_my_cpu;

			ExternalReference.c_map_op_code = (char)cmpnt->operationCode;

			if( MAP_Decode_IMSI_LU_ARGUMENT( &tfs_manager.imsi,
										     cmpnt ) != MAP_SUCCESS )
			{
				log_(LOG_ERROR,"TC-BEGIN: SCCP CD [%s] without IMSI",ac_dest);
			}
			else
			{
				log_(LOG_DEBUG2,"%s: TC-BEGIN: SCCP CD [%s] with IMSI[%.*s]",
						__FUNCTION__,
						ac_dest,
						tfs_manager.imsi.length,
						tfs_manager.imsi.value);
			}

			if( GT_mitt->address.length > 0 )
			{
				memcpy( &tfs_manager.GT_mitt,
						GT_mitt,
						sizeof(INS_AddressString) );

				memcpy( ac_mitt,
						tfs_manager.GT_mitt.address.value,
						tfs_manager.GT_mitt.address.length );
			}

			// Set throughput time start
			ExternalReference.Ts_in = JULIANTIMESTAMP(0);

			memcpy( tfs_manager.external_reference,
					(char *)&ExternalReference,
					sizeof(EXTERNAL_REF) );

			i_err = Func_MTS_SEND_Taskid( i_taskid_ts,
										  i_serverclass_ts,
										  0,
										  0,
										  (char *)&tfs_manager,
										  sizeof(ts_data) );

			switch( cmpnt->operationCode )
			{
				case UpdateGSMLocation_Request_OperationCode:
				{
					if( i_err )
					{
						i_op_to_do = RELAY;

						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ST_REQ_KO);

						EVT_manage( EVTN_REQ_TO_TS_ERROR,
									i_nbr_alert_msg,
									i_interval_time,
									'A',
									"IPC Err.[%d] with TS Manager process - Relaying",
									i_err );

						log_(LOG_ERROR,"GSM LU: MTS_SEND[%d:%d] to TS Manager failure - Err.[%d] - [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
									i_taskid_ts,
									i_serverclass_ts,
									i_err,
									ac_mitt,
									route_info->cg_addr.ssn,
									ac_dest,
									route_info->cd_addr.ssn);
					}
					else
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ST_REQ_OK);

						log_(LOG_DEBUG,"GSM LU: Steering req. to TS-Manager - [Cg=%s:%d] - [Cd=%s:%d] OK",
									ac_mitt,
									route_info->cg_addr.ssn,
									ac_dest,
									route_info->cd_addr.ssn);

						EVT_manage( EVTN_REQ_TO_TS_OK,
									i_nbr_alert_msg,
									i_interval_time,
									'D',
									"TS Manager process is alive" );
					}

					break;
				}

				case UpdateGPRSLocation_Request_OperationCode:
				{
					if( i_err )
					{
						i_op_to_do = RELAY;

						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ST_REQ_KO);

						EVT_manage( EVTN_REQ_TO_TS_ERROR,
									i_nbr_alert_msg,
									i_interval_time,
									'A',
									"IPC Err.[%d] with TS Manager process - Relaying",
									i_err );

						log_(LOG_ERROR,"GPRS LU: MTS_SEND[%d:%d] to TS Manager failure - Err.[%d] [Cg=%s:%d] - [Cd=%s:%d] - Relaying",
									i_taskid_ts,
									i_serverclass_ts,
									i_err,
									ac_mitt,
									route_info->cg_addr.ssn,
									ac_dest,
									route_info->cd_addr.ssn);
					}
					else
					{
						AddStat(STAT_MAPIRO_PREFIX_REGS,"MAPIN",TOT_ST_REQ_OK);

						log_(LOG_DEBUG,"GPRS LU: Steering req. to TS-Manager - [Cg=%s:%d] - [Cd=%s:%d] OK",
									ac_mitt,
									route_info->cg_addr.ssn,
									ac_dest,
									route_info->cd_addr.ssn);

						EVT_manage( EVTN_REQ_TO_TS_OK,
									i_nbr_alert_msg,
									i_interval_time,
									'D',
									"TS Manager process is alive" );
					}

					break;
				}
			}

            break;
        }

//        case RELAY:
//        {
//            switch( i_opcode )
//            {
//                case UpdateGSMLocation_Request_OperationCode:
//                {
//                    log_(LOG_ERROR,"RX GSM LU - [Cg=%s:%d] - [Wrong Cd=%s:%d] - No operation to do",
//                    			ac_mitt,
//                                route_info->cg_addr.ssn,
//                                ac_dest,
//                                route_info->cd_addr.ssn);
//
//                    break;
//                }
//
//                case UpdateGPRSLocation_Request_OperationCode:
//                {
//                    log_(LOG_ERROR,"RX GPRS LU - [Cg=%s:%d] - [Wrong Cd=%s:%d] - No operation to do",
//                    			ac_mitt,
//                                route_info->cg_addr.ssn,
//                                ac_dest,
//                                route_info->cd_addr.ssn);
//
//                    break;
//                }
//            }
//
//            break;
//        }
    }

    return i_op_to_do;
}

//void CheckSSN_HLR( short i_op,
//                   short i_ssn )
//{
//    if( i_ssn != HLR )
//    {
//        EVT_manage( EVTN_SSN_NOT_HLR,
//					0,
//					i_interval_time,
//					'A',
//					"Rec. MAP Op.[%d] with wrong SSN=[%d]",
//					i_op,
//					i_ssn );
//    }
//}

// print start/stop message on log_
void Msg_print( short i_type )
{
    log_ (LOG_INFO, "**************************");
    log_ (LOG_INFO, "***                    ***");
    log_ (LOG_INFO, "***  Traffic Steering  ***");
    log_ (LOG_INFO, "***       MAP-IN       ***");
    log_ (LOG_INFO, "***                    ***");
    log_ (LOG_INFO, "***       V 1.11       ***");
    log_ (LOG_INFO, "***                    ***");

    switch( i_type )
    {
        case _START_:
        {
            EVT_manage( EVTN_START,
						0,
						0,
						'N',
						"[%s] started",
						ac_my_process_name );

            log_ (LOG_INFO, "***      Started       ***");

            break;
        }

        case _STOP_:
        {
            EVT_manage( EVTN_STOP,
						0,
						0,
						'N',
						"[%s] stopped by user",
						ac_my_process_name );

            log_ (LOG_INFO, "***      Stopped       ***");

            break;
        }
    }

    log_ (LOG_INFO, "***                    ***");
    log_ (LOG_INFO, "**************************");
}

/****************************************************************************
***  Module Name:  Process_Initialization                                  **
***                                                                        **
***  Description:  This module is responsible for processing all of the    **
***                run-time parameters and determining if the process      **
***                has been started under the Node or in a stand-alone     **
***                environment.                                            **
*****************************************************************************/
void Process_Initialization (void)
{
    short           rc;
    short           i_proch[20];
    short           i_maxlen = sizeof (ac_my_process_name);
    char            *wrk_str;
    FW_ACTabled     AC_List;

    if ((wrk_str = getenv ("FILEINI")) != NULL)
    {
        memset(ac_filecfg,0x00, sizeof(ac_filecfg));
		memset(ac_my_process_name,0x00,sizeof(ac_my_process_name));
        strncpy(ac_filecfg,wrk_str,sizeof(ac_filecfg)-1);

        PROCESSHANDLE_GETMINE_ (i_proch);
        PROCESSHANDLE_DECOMPOSE_ ( i_proch,&i_my_cpu,
                                   ,,,,,
                                   ac_my_process_name,
                                   i_maxlen,
                                   &i_maxlen, );

		setChgFile(ac_filecfg,ac_filecfg_oss);

        if(!LoadParameters(ac_filecfg,LOAD))
        {
            exit(-1);
        }
        else
        {
            Msg_print( _START_ );

            // Initialize FWR
            // ********************************
            // Disable AC Name list management
            AC_List.ac_array_entries = 0;
            setFW_disableLookupACName();
            // ********************************
            rc = TCAP_InitializeFramework( &AC_List );

			if( rc != FW_IF_OK &&
				rc != FW_IF_NoOperation )
			{
				EVT_manage( EVTN_FW_INITIALIZE_KO,
							0,
							0,
							'A',
							"FW initialization failure - Err.[%d] - Exit",
							rc );

				log_(LOG_ERROR,"FW initialization failure - Exit" );

				exit(-1);
			}

			L_INITIALIZE_END();

            if(!Stat_init( "",
                           "",
                           "",
                           i_stat_group,
                           i_stat_max_register,
                           S_MAX_IDX_NUMBER ))
            {
                EVT_manage( EVTN_STAT_NOT_INIT,
							0,
							0,
							'A',
							"Stat_init failure - Exit" );

                log_(LOG_ERROR,"Stat_init failure - Exit");

                exit(-1);
            }
            else
            {
            	log_(LOG_INFO,"Network-Name[%s] - Network-ID[%d] - TFS Int.Routing[%s] - TFS VPC[%d]",
							vpc_status.ac_net_name,
							vpc_status.i_net_id,
							(i_internal_routing_strategy?"INTERNAL ROUTING SET":"NOT INTERNAL ROUTING SET"),
							vpc_status.i_vpc);

            	setFW_networkId((char)vpc_status.i_net_id);

            	if(i_stat_fw_param_loaded)
				{
					if( rc = (short)FW_StatOpen_No_Bump() ) // Open FW stat without BUMP_STAT functionality
					{
						EVT_manage( EVTN_STAT_NOT_INIT,
									0,
									0,
									'A',
									"Initialize FW Stats failure - Err.[%d]",
									rc);


						log_(LOG_ERROR,"Initialize FW Stats failure - Err.[%d]", rc);
					}
					else
						log_(LOG_INFO,"TFS FRW Stat_init successfully - FW Group[%d]", i_stat_fw_group);
				}
            }
        }
    }
    else
        exit(-1);
} // End Of Procedure: Process_Initialization

//
// Load parameters function. Load INI file
//
short LoadParameters( char *ac_PathCfgFile,
                      short i_reload )
{
    short    rc = 0;
    short    ret = 1;
    short	 i_tmp;
    int      found = 0;
    char     ac_value[255];
    char     *wrk_str;
    char     *ac_delimiters = ",;:-";

    memset(&vpc_status,0x00,sizeof(VPC_STATUS));

    SetDefaultSSN(HLR); // default

    /*******************
	** [EVT]
	********************/
	if( !i_reload )
	{
		rc = get_profile_string( ac_PathCfgFile,
								 "EVT",
								 "SSID-OWNER",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(ac_cSSID_Owner,ac_value,sizeof(ac_cSSID_Owner)-1);

				rc = get_profile_string( ac_PathCfgFile,
										 "EVT",
										 "SSID-NUMBER",
										 &found,
										 ac_value );
				if(!rc)
				{
					if(found)
					{
						i_nSSID_Number = (short)atoi(ac_value);

						rc = get_profile_string( ac_PathCfgFile,
												 "EVT",
												 "SSID-VERSION",
												 &found,
												 ac_value );
						if(!rc)
						{
							if(found)
							{
								strncpy(ac_cSSID_Version,ac_value,sizeof(ac_cSSID_Version)-1);

								//
								//  initialize EVT on $0
								//
								if (!sspevt_init( "TFS-IN",
												  ac_cSSID_Owner,
												  i_nSSID_Number,
												  ac_cSSID_Version ) )
								{
									EVT_manage_init();
								}
								else
									ret = 0;
							}
							else
								ret = 0;
						}
						else
							ret = 0;
					}
					else
						ret = 0;
				}
				else
					ret = 0;
			}
			else
				ret = 0;
		}
		else
			ret = 0;
	}

	if(i_reload >= 0 && ret)
	{
		if(!i_reload)
			i_nbr_alert_msg = 1; // Default value 1 msg

		rc = get_profile_string( ac_PathCfgFile,
								 "EVT",
								 "NBR-ALERT-MSG",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				i_tmp = (short)atoi(ac_value);
				if(i_tmp < 0)
				{
					if(!i_reload)
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [EVT][NBR-ALERT-MSG] - Set to 1 msg" );
					}
					else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [EVT][NBR-ALERT-MSG]" );
					}
				}
				else
					i_nbr_alert_msg = i_tmp;
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [EVT][NBR-ALERT-MSG] - Set to 1 msg" );
				}
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [EVT][NBR-ALERT-MSG]" );
		}
	}

	if(i_reload >= 0 && ret)
	{
		if(!i_reload)
			i_interval_time = 300; // Default value in seconds 300"

		rc = get_profile_string( ac_PathCfgFile,
								 "EVT",
								 "INTERVAL-ALERT-MSG-TIME",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				i_tmp = (short)atoi(ac_value);
				if(i_tmp < 0)
				{
					if(!i_reload)
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [EVT][INTERVAL-ALERT-MSG-TIME] - Set to 5'" );
					}
					else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [EVT][INTERVAL-ALERT-MSG-TIME]" );
					}
				}
				else
					i_interval_time = i_tmp;
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [EVT][INTERVAL-ALERT-MSG-TIME] - Set to 5'" );
				}
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [EVT][INTERVAL-ALERT-MSG-TIME]" );
		}
	}

    /*******************
    ** [COMMON]
    ********************/
    if(i_reload >= 0 && ret)
    {
    	if(!i_reload)
    		l_timeout_reload = (long)(15*60*100); // 15'

        rc = get_profile_string( ac_PathCfgFile,
                                "COMMON",
                                "TIMEOUT-RELOAD-PARAM",
                                &found,
                                ac_value );
        if(!rc)
        {
            if(found)
            {
                l_timeout_reload= (long)(atol(ac_value)*60*100);
                if(l_timeout_reload < 6000)
                {
                    l_timeout_reload = 6000;

                    EVT_manage( EVTN_WRONG_PARAM,
								0,
								0,
								'A',
								"Wrong [COMMON][TIMEOUT-RELOAD-PARAM] - Set to 1'" );
                }
            }
            else
            {
            	if(!i_reload)
            	{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [COMMON][TIMEOUT-RELOAD-PARAM] - Set to 15'" );
            	}
            }
        }
        else
        {
        	ret = 0;

        	EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [COMMON][TIMEOUT-RELOAD-PARAM]" );
        }
    }

    if(i_reload >= 0 && ret)
	{
    	if(!i_reload)
    		i_manage_GPRS_UpLoc = 0; // Default Always Relay

		rc = get_profile_string( ac_PathCfgFile,
								"COMMON",
								"MANAGE-GPRS-UPDATE-LOCATION",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				i_tmp = (short)atoi(ac_value);
				if( i_tmp < 0 ||
					i_tmp > 2 )
				{
					if(!i_reload)
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [COMMON][MANAGE-GPRS-UPDATE-LOCATION] - 0,1 or 2");
					}
					else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [COMMON][MANAGE-GPRS-UPDATE-LOCATION]");
					}
				}
				else
					i_manage_GPRS_UpLoc = i_tmp;
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [COMMON][MANAGE-GPRS-UPDATE-LOCATION] - Set to 0" );
				}
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [COMMON][MANAGE-GPRS-UPDATE-LOCATION]" );
		}
	}

    /*******************
	* [PREFIX-ADDR-LIST]
	********************/
	if(!i_reload && ret )
	{
		rc = get_profile_string( ac_PathCfgFile,
								"PREFIX-ADDR-LIST",
								"SCCP-CALLING-PREFIX-LIST-OWNER-TFS",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(ac_cg_prefix_list_owner_tfs,ac_value,sizeof(ac_cg_prefix_list_owner_tfs)-1);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PREFIX-ADDR-LIST][SCCP-CALLED-PREFIX-LIST-OWNER-TFS]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PREFIX-ADDR-LIST][SCCP-CALLED-PREFIX-LIST-OWNER-TFS]" );
		}
	}

	if(!i_reload && ret )
	{
		rc = get_profile_string( ac_PathCfgFile,
								"PREFIX-ADDR-LIST",
								"SCCP-CALLED-PREFIX-LIST-OWNER-TFS",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(ac_cd_prefix_list_owner_tfs,ac_value,sizeof(ac_cd_prefix_list_owner_tfs)-1);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PREFIX-ADDR-LIST][SCCP-CALLED-PREFIX-LIST-OWNER-TFS]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PREFIX-ADDR-LIST][SCCP-CALLED-PREFIX-LIST-OWNER-TFS]" );
		}
	}

	if(!i_reload && ret )
	{
		rc = get_profile_string( ac_PathCfgFile,
								"PREFIX-ADDR-LIST",
								"SCCP-CALLING-LU-GPRS-WHITELIST",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(ac_cg_lu_gprs_whitelist,ac_value,sizeof(ac_cg_lu_gprs_whitelist)-1);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PREFIX-ADDR-LIST][SCCP-CALLING-LU-GPRS-WHITELIST]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PREFIX-ADDR-LIST][SCCP-CALLING-LU-GPRS-WHITELIST]" );
		}
	}

    /*******************
    ** [PC]
    ********************/
	if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								"PC",
								"TFS-NET-NAME",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(vpc_status.ac_net_name,ac_value,sizeof(vpc_status.ac_net_name)-1);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PC][TFS-NET-NAME]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PC][TFS-NET-NAME]" );
		}
	}

	if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								 "PC",
								 "TFS-NET-ID",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				vpc_status.i_net_id = (unsigned short)atoi(ac_value);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PC][TFS-NET-ID]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PC][TFS-NET-ID]" );
		}
	}

	if(i_reload >= 0 && ret)
	{
		// To cause the INS Router to send a message with “Route on Global Title” set in the SCCP’s called party address to an adjacent node (e.g. STP),
		// the application must send to some DPC that is NOT one of the local point codes.
		// A MTP3 Routing Label DPC value of zero results in correct routing of messages out of the INS to one of the nodes identified in the INS document “Configuration Planning Guide”.

		if(!i_reload)
			i_internal_routing_strategy = NO_INTERNAL_ROUTING_STRATEGY; // Default NO_INTERNAL_ROUTING_STRATEGY

		rc = get_profile_string( ac_PathCfgFile,
								 "PC",
								 "TFS-INTERNAL-ROUTING-STRATEGY",
								 &found,
								 ac_value );

		if(!rc)
		{
			if(found)
			{
				i_tmp = (short)atoi(ac_value);

				if( i_tmp < 0 ||
					i_tmp > 1 )
				{
					if(!i_reload)
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][TFS-INTERNAL-ROUTING-STRATEGY] - Set to 0" );
					}
					else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][TFS-INTERNAL-ROUTING-STRATEGY] - 0 or 1" );
					}
				}
				else
					i_internal_routing_strategy = i_tmp;
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [PC][TFS-INTERNAL-ROUTING-STRATEGY] - Set to 0" );
				}
			}
		}
		else
		{
			if(!i_reload)
			{
				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PC][TFS-INTERNAL-ROUTING-STRATEGY] - Set to 0" );
			}
		}
	}

	if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								 "PC",
								 "TFS-VPC",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				if(i_internal_routing_strategy == INTERNAL_ROUTING_STRATEGY)
					vpc_status.i_vpc = 0; // forced to 0
				else
					vpc_status.i_vpc = (short)atoi(ac_value);
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [PC][TFS-VPC]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PC][TFS-VPC]" );
		}
	}

    if(i_reload >= 0 && ret)
    {
    	if(!i_reload)
    		i_auto_allow_vpc = 0;

        rc = get_profile_string( ac_PathCfgFile,
                                 "PC",
                                 "AUTO-ALLOW-VPC",
                                 &found,
                                 ac_value );
        if(!rc)
        {
            if(found)
            {
                i_tmp = (short)atoi(ac_value);
                if( i_tmp < 0 ||
                	i_tmp > 1 )
                {
                	if(!i_reload)
                	{
                		EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][AUTO-ALLOW-VPC] - Set to 0" );
                	}
                	else
                	{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][AUTO-ALLOW-VPC] - 0 or 1" );
                	}
                }
                else
                	i_auto_allow_vpc = i_tmp;
            }
            else
            {
            	if(!i_reload)
            	{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [PC][AUTO-ALLOW-VPC] - Set to 0" );
            	}
            }
        }
        else
        {
        	ret = 0;

        	EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PC][AUTO-ALLOW-VPC]" );
        }
    }

    if(i_reload >= 0 && ret)
    {
    	if(!i_reload)
    		l_timeout_allow_vpc = (long)(5*60*100); // 5'

        rc = get_profile_string( ac_PathCfgFile,
                                "PC",
                                "VPC-ALLOW-TIMEOUT",
                                &found,
                                ac_value );
        if(!rc)
        {
            if(found)
            {
            	l_timeout_allow_vpc = (long)(atol(ac_value)*60*100);
                if( l_timeout_allow_vpc < 0 )
                {
                	if(!i_reload)
                	{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][VPC-ALLOW-TIMEOUT] - Set to 5'" );
                	}
                	else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [PC][VPC-ALLOW-TIMEOUT]" );
					}
                }
            }
            else
            {
            	if(!i_reload)
            	{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [PC][VPC-ALLOW-TIMEOUT] - Set to 5'" );
            	}
            }
        }
        else
        {
            ret = 0;

            EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [PC][VPC-ALLOW-TIMEOUT]" );
        }
    }

    if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								"PC",
								"HLR-SSN",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				i_hlr_ssn = (short) atoi(ac_value);
				SetDefaultSSN(i_hlr_ssn);

				EVT_manage( EVTN_DEFAULT_HLR_SSN,
							0,
							0,
							'N',
							"Default HLR-SSN value set by user to [%d]",
							i_hlr_ssn );
			}
		}
	}

    /*******************
    ** [IPC]
    ********************/
    if(i_reload >= 0 && ret)
    {
        rc = get_profile_string( ac_PathCfgFile,
                                "IPC",
                                "MTS-TID-SVRC-TFS-MANAGER",
                                &found,
                                ac_value );
        if(!rc)
        {
            if(found)
            {
            	wrk_str = strtok( ac_value, ac_delimiters);
				if (wrk_str)
				{
					if ( !(i_taskid_ts = (short)atoi(wrk_str)) )
					{
						ret = 0;

						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong TaskId [IPC][MTS-TID-SVRC-TFS-MANAGER]" );
					}
					else
					{
						wrk_str = strtok( NULL, ac_delimiters);
						if (wrk_str)
						{
							if ( !(i_serverclass_ts = (short)atoi(wrk_str)) )
							{
								ret = 0;

								EVT_manage( EVTN_WRONG_PARAM,
											0,
											0,
											'A',
											"Wrong SrvClass [IPC][MTS-TID-SVRC-TFS-MANAGER]" );
							}
						}
						else
						{
							ret = 0;

							EVT_manage( EVTN_WRONG_PARAM,
										0,
										0,
										'A',
										"Wrong SrvClass [IPC][MTS-TID-SVRC-TFS-MANAGER]" );
						}
					}
				}
            }
            else
            {
            	ret = 0;

            	EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [IPC][MTS-TID-SVRC-TFS-MANAGER]" );
            }
        }
        else
        {
        	ret = 0;

        	EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [IPC][MTS-TID-SVRC-TFS-MANAGER]" );
        }
    }

    if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								"IPC",
								"MTS-TID-SVRC-GTTS",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				wrk_str = strtok( ac_value, ac_delimiters);
				if (wrk_str)
				{
					if ( !(i_taskid_gtt = (short)atoi(wrk_str)) )
					{
						ret = 0;

						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong TaskId [IPC][MTS-TID-SVRC-GTTS]" );
					}
					else
					{
						wrk_str = strtok( NULL, ac_delimiters);
						if (wrk_str)
						{
							if ( !(i_serverclass_gtt = (short)atoi(wrk_str)) )
							{
								ret = 0;

								EVT_manage( EVTN_WRONG_PARAM,
											0,
											0,
											'A',
											"Wrong SrvClass [IPC][MTS-TID-SVRC-GTTS]" );
							}
						}
						else
						{
							ret = 0;

							EVT_manage( EVTN_WRONG_PARAM,
										0,
										0,
										'A',
										"Wrong SrvClass [IPC][MTS-TID-SVRC-GTTS]" );
						}
					}
				}
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [IPC][MTS-TID-SVRC-GTTS]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [IPC][MTS-TID-SVRC-GTTS]" );
		}
	}

    if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								"IPC",
								"MTS-TID-SVRC-MAPRELAY",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				wrk_str = strtok( ac_value, ac_delimiters);
				if (wrk_str)
				{
					if ( !(i_taskid_relay = (short)atoi(wrk_str)) )
					{
						ret = 0;

						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong TaskId [IPC][MTS-TID-SVRC-MAPRELAY]" );
					}
					else
					{
						wrk_str = strtok( NULL, ac_delimiters);
						if (wrk_str)
						{
							if ( !(i_serverclass_relay = (short)atoi(wrk_str)) )
							{
								ret = 0;

								EVT_manage( EVTN_WRONG_PARAM,
											0,
											0,
											'A',
											"Wrong SrvClass [IPC][MTS-TID-SVRC-MAPRELAY]" );
							}
						}
						else
						{
							ret = 0;

							EVT_manage( EVTN_WRONG_PARAM,
										0,
										0,
										'A',
										"Wrong SrvClass [IPC][MTS-TID-SVRC-MAPRELAY]" );
						}
					}
				}
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [IPC][MTS-TID-SVRC-MAPRELAY]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [IPC][MTS-TID-SVRC-MAPRELAY]" );
		}
	}

    if(i_reload >= 0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								"IPC",
								"MTS-TID-SVRC-MAPOUT",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				wrk_str = strtok( ac_value, ac_delimiters);
				if (wrk_str)
				{
					if ( !(i_taskid_mapout = (short)atoi(wrk_str)) )
					{
						ret = 0;

						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong TaskId [IPC][MTS-TID-SVRC-MAPOUT]" );
					}
					else
					{
						wrk_str = strtok( NULL, ac_delimiters);
						if (wrk_str)
						{
							if ( !(i_serverclass_mapout = (short)atoi(wrk_str)) )
							{
								ret = 0;

								EVT_manage( EVTN_WRONG_PARAM,
											0,
											0,
											'A',
											"Wrong SrvClass [IPC][MTS-TID-SVRC-MAPOUT]" );
							}
						}
						else
						{
							ret = 0;

							EVT_manage( EVTN_WRONG_PARAM,
										0,
										0,
										'A',
										"Wrong SrvClass [IPC][MTS-TID-SVRC-MAPOUT]" );
						}
					}
				}
			}
			else
			{
				ret = 0;

				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [IPC][MTS-TID-SVRC-MAPOUT]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [IPC][MTS-TID-SVRC-MAPOUT]" );
		}
	}

    /*******************
	** [LOG]
	********************/
	if(!i_reload && ret)
	{
		if(!i_reload)
			i_num_days_of_log = 3; // 3 giorni

		rc = get_profile_string( ac_PathCfgFile,
								 "LOG",
								 "PATH-LOG",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				strncpy(ac_path_log_file,ac_value,sizeof(ac_path_log_file)-1);

				rc = get_profile_string( ac_PathCfgFile,
										 "LOG",
										 "NUM-DAYS-OF-LOG",
										 &found,
										 ac_value );
				if(!rc)
				{
					if(found)
					{
						i_tmp = (short)atoi (ac_value);
						if(i_tmp < 0)
						{
							i_num_days_of_log = 3;

							EVT_manage( EVTN_WRONG_PARAM,
										0,
										0,
										'A',
										"Wrong [LOG][NUM-DAYS-OF-LOG] - Set to 3gg" );
						}
						else
							i_num_days_of_log = i_tmp;
					}
					else
					{
						if(!i_reload)
						{
							EVT_manage( EVTN_PARAM_MISSING,
										0,
										0,
										'A',
										"Missing [LOG][NUM-DAYS-OF-LOG] - Set to 3gg" );
						}
					}

					rc = (short)log_init ( ac_path_log_file,
										   ac_my_process_name + 1,
										   i_num_days_of_log );

					if(!rc)
					{
						log_param_filecreate ( 1024 /*filecreate_primary_extent_size*/,
											   1024 /*filecreate_secondary_extent_size*/,
												900 /*filecreate_maximum_extents */ );
					}
				}
				else
				{
					ret = 0;
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [LOG][NUM-DAYS-OF-LOG]" );
				}
			}
			else
			{
				ret = 0;
				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [LOG][PATH-LOG]" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [LOG][PATH-LOG]" );
		}
	}

	if(i_reload>=0 && ret)
	{
		if(!i_reload)
			i_trace_level = LOG_ERROR;

		rc = get_profile_string( ac_PathCfgFile,
								 "LOG",
								 "TRACE-LEVEL",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				i_tmp = (short)atoi (ac_value);
				if(i_tmp < 0)
				{
					if(!i_reload)
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [LOG][TRACE-LEVEL] - Set to ERROR" );
					}
					else
					{
						EVT_manage( EVTN_WRONG_PARAM,
									0,
									0,
									'A',
									"Wrong [LOG][TRACE-LEVEL]" );
					}
				}
				else
					i_trace_level = i_tmp;
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [LOG][TRACE-LEVEL] - Set to ERROR" );
				}
			}

			if( i_trace_level >= LOG_DEBUG )
			{
				log_param( i_trace_level,
						   LOG_UNBUFFERED,
						   "" );
			}
			else
			{
				log_param( i_trace_level,
						   LOG_STAT,
						   "" );
			}
		}
		else
		{
			ret = 0;

			EVT_manage( EVTN_PARAM_MISSING,
						0,
						0,
						'A',
						"Missing [LOG][TRACE-LEVEL]" );
		}
	}

	if(i_reload>=0 && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								 "LOG",
								 "TRACE-STRING",
								 &found,
								 ac_value );
		if(!rc)
		{
			if(found)
			{
				if(ac_value[0])
					log_set_trace(ac_value);
				else
					log_reset_trace();
			}
		}
	}

	/*******************
	** [STAT]
	********************/
	if(!i_reload && ret)
	{
		rc = get_profile_string( ac_PathCfgFile,
								 "STAT",
								 "NBR-MAX-REG",
								 &found,
								 ac_value );

		if(!rc)
		{
			if(found)
			{
				i_stat_max_register=(short)atoi(ac_value);

				rc = get_profile_string( ac_PathCfgFile,
										 "STAT",
										 "GROUP",
										 &found,
										 ac_value );

				if(!rc)
				{
					if(found)
						i_stat_group = (short)atoi(ac_value);
				}
				else
					ret = 0;
			}
			else
			{
				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [STAT][NBR-MAX-REG]" );
			}
		}
		else
			ret = 0;
	}

	if(!i_reload && ret)
	{
		i_stat_fw_param_loaded = 0;

		rc = get_profile_string( ac_PathCfgFile,
								 "STAT",
								 "FW-GROUP",
								 &found,
								 ac_value );

		if(!rc)
		{
			if(found)
			{
				i_stat_fw_param_loaded = 1;
				i_localMaxRegs 		   = 100;
				i_stat_fw_group 	   = (short)atoi(ac_value);

				setFWStatRegSet("FW-CALL-PROC    ");
				setFWStatStatsGroup(i_stat_fw_group);
				setFWStatMaxRegs(i_localMaxRegs);
			}
			else
			{
				EVT_manage( EVTN_PARAM_MISSING,
							0,
							0,
							'A',
							"Missing [STAT][FW-GROUP]" );
			}
		}
	}

	if(i_reload>=0 && ret)
	{
		if(!i_reload)
			l_stat_bump_interval = (long)(5*60); // 5 '

		rc = get_profile_string( ac_PathCfgFile,
								 "STAT",
								 "TIMEOUT-BUMP",
								 &found,
								 ac_value );

		if(!rc)
		{
			if(found)
			{
				l_stat_bump_interval = (long)(atol(ac_value) * 60);
				if(l_stat_bump_interval < 60)
					l_stat_bump_interval = (long)(60*1); // 1'
			}
			else
			{
				if(!i_reload)
				{
					EVT_manage( EVTN_PARAM_MISSING,
								0,
								0,
								'A',
								"Missing [STAT][TIMEOUT-BUMP] - Set to 5'" );
				}
			}
		}
		else
		{
			ret = 0;
		}
	}

	/*******************
	** [DUMP]
	********************/
	if(i_reload >= 0 && ret)
	{
		if(!i_reload)
			i_dump_msg = 0;

		rc = get_profile_string( ac_PathCfgFile,
								"DUMP",
								"DUMP-RAW-MSG-BEFORE-SEND",
								&found,
								ac_value );
		if(!rc)
		{
			if(found)
			{
				i_dump_msg = (short)atoi(ac_value);

				DumpMsgBeforeSend((char)i_dump_msg);
			}
		}
	}

	return(ret);
} // LoadParameters
