#ifndef _GTTSTAT_H_
#define _GTTSTAT_H_

#define RICHIESTE_RICEVUTE          1
#define RISPOSTE_SEND_OK            2
#define RISPOSTE_SEND_KO            3
#define RISPOSTE_ERRORE_SU_REPLY    4
#define RISPOSTE_POSITIVE           5
#define RISPOSTE_NEGATIVE           6
#define TRANSAZIONI_ENTRO_5_MSEC    7
#define TRANSAZIONI_ENTRO_10_MSEC   8
#define TRANSAZIONI_ENTRO_25_MSEC   9
#define TRANSAZIONI_ENTRO_50_MSEC   10
#define TRANSAZIONI_ENTRO_75_MSEC   11
#define TRANSAZIONI_ENTRO_100_MSEC  12
#define TRANSAZIONI_ENTRO_250_MSEC  13
#define TRANSAZIONI_ENTRO_500_MSEC  14
#define TRANSAZIONI_ENTRO_750_MSEC  15
#define TRANSAZIONI_ENTRO_1_SEC     16
#define TRANSAZIONI_ENTRO_2_SEC     17
#define TRANSAZIONI_ENTRO_3_SEC     18
#define TRANSAZIONI_OLTRE_3_SEC     19


#endif
