CREATE SET TABLE BIC_ODS_SA.SA_CRM_INDIRIZZO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      TIPO_ELABORAZIONE CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      BUSINESS_PARTNER VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ID_CLIENTE_BIC VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      ID_INDIRIZZO_SAP VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      ID_INDIRIZZO_BIC VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      ID_TIPO_RIFERIMENTO_INDIRIZZO CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      CODICE_TOPONIMO VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      NOME_STRADA VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC,
      NUM_CIVICO VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      CAP VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      DESC_COMUNE_CLI VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      SIGLA_PROVINCIA_CLI VARCHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      COD_NAZIONE_CLI VARCHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      CASELLA_POSTALE VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      INDIRIZZO_CERTIFICATO CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      NOME_FLUSSO VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      DT_RIF DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      DESC_LOCALITA_CLI VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRESSO VARCHAR(40) CHARACTER SET LATIN NOT CASESPECIFIC,
      FABBRICATO VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      COD_SISTEMA_SORGENTE VARCHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL DEFAULT 'CRM')
UNIQUE PRIMARY INDEX ( ID_INDIRIZZO_SAP ,ID_TIPO_RIFERIMENTO_INDIRIZZO );

